name: Run Tests

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "README.md"
      - "LICENSE"

jobs:
  test:
    runs-on: ubuntu-latest-m

    env:
      SKIP_LOCAL_ENV: "true"
      REGISTRY: ghcr.io/fhenixprotocol/nitro
    strategy:
      matrix:
        node-version: [20.x, 22.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install Dependencies
        run: pnpm install
      - name: Build Package
        run: pnpm build
      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}
      - name: Run localfhenix
        run: |
          docker run -p 8545:8547 -p 8548:8548 -p 5000:3000 -e FHEOS_SECURITY_ZONES=2 ghcr.io/fhenixprotocol/nitro/localfhenix:latest &
      - name: Run Tests
        # wait for localfhenix to start
        run: sleep 20 && pnpm test
      - name: Run ESLint
        run: pnpm lint
      - name: Run prettier
        run: pnpm prettier-ci

  test-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install Dependencies
        run: pnpm install
      - name: Test Build
        run: pnpm build
